### ISSUE TITLE
hyprdim 2.2.6 only works on Hyprland v0.42.0+

### ISSUE THREAD

**Issue by theailer** [donovanglover/hyprdim#103]
# Bug Report

## Environment

- Output of `uname -a`:
` Linux stationary 6.10.3-2-cachyos-sched-ext  #1 SMP PREEMPT_DYNAMIC Sun, 04 Aug 2024 10:27:51 +0000 x86_64 GNU/Linux`
- Output of `hyprdim -V`:
`hyprdim 2.2.6`
- Output of `hyprctl version`:
```
Hyprland, built from branch  at commit 918d8340afd652b011b937d29d5eea0be08467f5  (flake.lock: update).
Date: Tue Jun 25 12:06:02 2024
Tag: v0.41.2, commits: 4886

flags: (if any)

```
## Expected Behavior
hyprdim should start

## Current Behavior
It crashes with:
```
thread 'main' panicked at src/lib.rs:85:48:
called `Result::unwrap()` on an `Err` value: SerdeError(Error("invalid type: boolean `false`, expected u8", line: 21, column: 23))
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Step to Reproduce
start hyprdim in terminal with command hyprdim

## Priorities
Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/donovanglover/hyprdim/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by donovanglover** [comment]
Unfortunately 2.2.6 only works with Hyprland v0.42.0 and above. Will pin this issue for people to see.

Long-term backwards compatibility would be nice but this isn't currently supported by [hyprland-rs](https://github.com/hyprland-community/hyprland-rs)

**Comment by donovanglover** [comment]
I looked into adding backwards compatibility support but the solution I came up with wasn't ideal.

For future releases I can show a better error message if the Hyprland version is too low.

**Comment by theailer** [comment]
Ah thanks for the info. Installed hyprland-git from AUR and now it works

**Comment by donovanglover** [comment]
Done in https://github.com/donovanglover/hyprdim/commit/f8ac9bc45cafc3161b7bf4f76c73d50b0465daa6
