### ISSUE TITLE
Won't install on Arch

### ISSUE THREAD

**Issue by theailer** [donovanglover/hyprdim#83]
# Bug Report

## Environment

- Output of `uname -a`:
`Linux stationary 6.8.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 05 Apr 2024 00:14:23 +0000 x86_64 GNU/Linux`

- Output of `hyprdim -V`:
Not applicable
- Output of `hyprctl version`:
Hyprland, built from branch v0.38.1-b at commit 360ede79d124ffdeebbe8401f1ac4bc0dbec2c91  (props: bump ver to 0.38.1)

## Expected Behavior
Package should install without errors

## Current Behavior
Package install fails stating wrong version of rustc is installed:
`
==> Starting build()...
error: package `clap v4.5.4` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.72.0
Either upgrade to rustc 1.74 or newer, or use
cargo update -p clap@4.5.4 --precise ver
where `ver` is the latest version of `clap` supporting rustc 1.72.0
==> ERROR: A failure occurred in build().
`
## Step to Reproduce
yay -S hyprdim

## Priorities
Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/donovanglover/hyprdim/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by donovanglover** [comment]
Hi can you try updating your system with `sudo pacman -Syu`? rustc 1.72.0 is from [August 2023](https://gitlab.archlinux.org/archlinux/packaging/packages/rust/-/commits/main)

**Comment by theailer** [comment]
Ah it seemed I had rustup installed instead of rust. 
Installing the package rust fixed the issue.
